export const cards = [
  {
    id: 1,
    title: "AI Artists",
    desc: "Add talent to AI",
    img: "https://images.pexels.com/photos/8386437/pexels-photo-8386437.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    lnk: "/services?cat=ai",
  },
  {
    id: 2,
    title: "Logo Design",
    desc: "Build yor brand",
    img: "https://images.pexels.com/photos/57690/pexels-photo-57690.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    lnk: "/services?cat=design",
  },
  {
    id: 3,
    title: "Digital Marketing",
    desc: "Get marketing strategies",
    img: "https://images.pexels.com/photos/3194519/pexels-photo-3194519.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    lnk: "/services?cat=digmarket",
  },
  {
    id: 4,
    title: "Music and Audio",
    desc: "Get custom music",
    img: "https://images.pexels.com/photos/4491536/pexels-photo-4491536.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    lnk: "/services?cat=music",
  },
  {
    id: 5,
    title: "Video And Animation",
    desc: "Build your own video trailer",
    img: "https://images.pexels.com/photos/9669045/pexels-photo-9669045.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    lnk: "/services?cat=animation",
  },
  {
    id: 6,
    title: "web Development",
    desc: "Customize your site",
    img: "https://images.pexels.com/photos/1779487/pexels-photo-1779487.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    lnk: "/services?cat=web",
  },
  {
    id: 7,
    title: "Business",
    desc: "Unlock growth online",
    img: "https://images.pexels.com/photos/3184287/pexels-photo-3184287.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    lnk: "/services?cat=business",
  },
  {
    id: 8,
    title: "Lifestyle",
    desc: "Color you dreams",
    img: "https://images.pexels.com/photos/4553618/pexels-photo-4553618.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    lnk: "/services?cat=lifestyle",
  },
  {
    id: 9,
    title: "Photography",
    desc: "Get Best photos ever",
    img: "https://images.pexels.com/photos/4340792/pexels-photo-4340792.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    lnk: "/services?cat=photo",
  },
  {
    id: 10,
    title: "Writing and Translation",
    desc: "Get Best writings ever",
    img: "https://images.pexels.com/photos/3278767/pexels-photo-3278767.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    lnk: "/services?cat=write",
  },
];

export const projects = [
  {
    id: 1,
    img: "https://images.pexels.com/photos/1462935/pexels-photo-1462935.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Web and Mobile Design",
    username: "Anna Bell",
  },
  {
    id: 2,
    img: "https://images.pexels.com/photos/270408/pexels-photo-270408.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Logo Design",
    username: "Morton Green",
  },
  {
    id: 3,
    img: "https://images.pexels.com/photos/4144923/pexels-photo-4144923.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Animated GIFs",
    username: "Emmett Potter",
  },
  {
    id: 4,
    img: "https://images.pexels.com/photos/4348404/pexels-photo-4348404.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Packaging Design",
    username: "Freddie Johnston",
  },
  {
    id: 5,
    img: "https://images.pexels.com/photos/4458554/pexels-photo-4458554.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Social Media Design",
    username: "Audrey Richards",
  },
  {
    id: 6,
    img: "https://images.pexels.com/photos/4465831/pexels-photo-4465831.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1036627/pexels-photo-1036627.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Illustration",
    username: "Dalton Hudson",
  },
  {
    id: 7,
    img: "https://images.pexels.com/photos/6077368/pexels-photo-6077368.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1858175/pexels-photo-1858175.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Book Design",
    username: "Hannah Dougherty",
  },
  {
    id: 8,
    img: "https://images.pexels.com/photos/4065876/pexels-photo-4065876.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1680175/pexels-photo-1680175.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Digital Marketing",
    username: "Ward Brewer",
  },
];
